package com.sahil.online.judge.entity;

public enum Status {
    ACCEPTED,
    WRONG_ANSWER,
    TIME_LIMIT_EXCEEDED,
    COMPILATION_ERROR,
    RUNTIME_ERROR_SIGSEGV,
    RUNTIME_ERROR_SIGFPE,
    RUNTIME_ERROR_SIGABRT,
    RUNTIME_ERROR_NZEC,
    RUNTIME_ERROR_OTHER,
    INTERNAL_ERROR,
    EXEC_FORMAT_ERROR,
    RUNTIME_ERROR_SIGXFSZ
}
